name: mobile
description: Nerdy News is a News App where News is collected from the top Comics and Superhero update sites. Get updated on every scroll in an easy and fantastic way. We cover Hollywood Movies, TV Shows, Comics, Games and Anime from Popular pop culture.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  akar_icons_flutter: ^1.1.16
  analytics:
    path: /Volumes/Work/projects/news/nerdy-news/mobile/packages/analytics
  appinio_social_share: ^0.2.6
  auth:
    path: ./packages/auth
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  env_reader: ^1.5.0
  equatable: ^2.0.5
  feedback:
    path: ./packages/feedback
  firebase_core: ^2.17.0
  firebase_performance: ^0.9.2+7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_html: ^3.0.0-beta.2
  flutter_html_audio: ^3.0.0-beta.2
  flutter_html_iframe: ^3.0.0-beta.2
  flutter_html_svg: ^3.0.0-beta.2
  flutter_html_video: ^3.0.0-beta.2
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  get_it: ^7.6.4
  google_fonts: ^5.1.0
  html: ^0.15.4
  image_picker: ^1.0.4
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  news:
    path: ./packages/news
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  provider: ^6.0.5
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  supabase_flutter: ^1.10.16
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter_gen:
  line_length: 80 # Optional (default: 80)
  output: lib/gen/ # Optional (default: lib/gen/)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    enabled: true
    outputs:
      class_name: MyColors
    inputs:
      - assets/colors/light.xml
      - assets/colors/dark.xml


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/env/
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages