name: news
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
  
dependencies:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  supabase: ^1.11.3
